---
- name: Install and configure MySQL on localhost
  hosts: localhost
  become: yes
  tasks:

    - name: Set MySQL root password before installation
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password'
        value: 'MyStrongPass123!'
        vtype: 'password'

    - name: Confirm MySQL root password again
      debconf:
        name: 'mysql-server'
        question: 'mysql-server/root_password_again'
        value: 'MyStrongPass123!'
        vtype: 'password'

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes
